name: OMEstudios
favicon: null
layout_spectrum: 0.4923405854497105
typography_spectrum: 0.29716
title: OME studios
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f5f5'
    - '#111111'
    - '#ababad'
    - '#848484'
    - '#414141'
  brandStrength: 0.18155694752931595
  lightness: 0.5821307976730168
  saturation: 0.7240819022990763
  rhythmicContrast: 0.2381169619038701
purpose: []
