title: OME studios
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7240819022990763
  brandStrength: 0.1815569475293159
  rhythmicContrast: 0.2381169619038701
  brandColors:
    - '#f5f5f5'
    - '#111111'
    - '#ababad'
    - '#848484'
    - '#414141'
  lightness: 0.5821307976730168
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: OMEstudios
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.29716
layout_spectrum: 0.5461869
